set_property IOSTANDARD LVCMOS33 [get_ports dspclk]
set_property IOSTANDARD LVCMOS33 [get_ports hid_clk]
set_property IOSTANDARD LVCMOS33 [get_ports hid_dat]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN W5 [get_ports dspclk]
set_property PACKAGE_PIN C17 [get_ports hid_clk]
set_property PACKAGE_PIN B17 [get_ports hid_dat]
set_property PACKAGE_PIN U18 [get_ports reset]

set_property PULLUP true [get_ports hid_clk]
set_property PULLUP true [get_ports hid_dat]

set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]

#ADD
create_clock -period 10.000 -name dspclk -waveform {0.000 5.000} [get_ports dspclk]

set_property IOSTANDARD LVCMOS33 [get_ports pari_err]
set_property PACKAGE_PIN L1 [get_ports pari_err]
